[project]
name = "rag-chatbot-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Spador", email = "sp3466@rit.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "deepeval>=4.2.0",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.1",
    "langchain-openai>=1.6.0",
    "langchain-text-splitters>=1.1.2",
    "openai>=3.7.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
rag-chatbot-eval = "rag_chatbot_eval:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
